# Generated by Django 5.1.5 on 2025-01-26 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.TextField(blank=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TimeCreated', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('auto', 'Samochód'), ('house', 'Cały dom'), ('vacuum', 'odkurzanie'), ('sweep_mop', 'Zamiatanie i mycie podłóg'), ('other', 'Inne')], default='other', max_length=10)),
                ('ExpiryDate', models.DateTimeField()),
                ('Status', models.CharField(choices=[('blocked', 'Zablokwane'), ('active', 'Aktywne'), ('closed', 'Zakończone')], default='active', max_length=10)),
                ('Location', models.CharField(max_length=256)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
