# Generated by Django 5.1.5 on 2025-01-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_offer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='State',
            field=models.CharField(choices=[('dolnoslaskie', 'Dolnośląskie'), ('kujawsko_pomorskie', 'Kujawsko-Pomorskie'), ('lubelskie', 'Lubelskie'), ('lubuskie', 'Lubuskie'), ('lodzkie', 'Łódzkie'), ('malopolskie', 'Małopolskie'), ('mazowieckie', 'Mazowieckie'), ('opolskie', 'Opolskie'), ('podkarpackie', 'Podkarpackie'), ('podlaskie', 'Podlaskie'), ('pomorskie', 'Pomorskie'), ('slaskie', 'Śląskie'), ('swietokrzyskie', 'Świętokrzyskie'), ('warminsko_mazurskie', 'Warmińsko-Mazurskie'), ('wielkopolskie', 'Wielkopolskie'), ('zachodniopomorskie', 'Zachodniopomorskie')], default='zachodniopomorskie', max_length=20),
            preserve_default=False,
        ),
    ]
