# Generated by Django 5.1.5 on 2025-02-06 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_added_state_to_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Description', models.TextField(blank=True)),
                ('TimeCreated', models.DateTimeField(auto_now_add=True)),
                ('Offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.offer')),
                ('Reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
