# Generated by Django 5.1.5 on 2025-04-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
